services:
  convfinqa-service:
    build:
      context: .
    image: convfinqa-service:latest
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-OPENAI_API_KEY}
      DATA_PATH: ${DATA_PATH:-data/convfinqa_dataset.json}
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "src.service:app", "--host", "0.0.0.0", "--port", "8000" ]